MLIR: lib/Dialect/Affine/Transforms/AffineParallelNormalize.cpp File Reference
AffineParallelNormalize.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/IR/PatternMatch.h"
Functions
void normalizeAffineParallel (AffineParallelOp op)
Normalize a affine.parallel op so that lower bounds are 0 and steps are 1.
Function Documentation
normalizeAffineParallel()
void normalizeAffineParallel (AffineParallelOp op)
Normalize a affine.parallel op so that lower bounds are 0 and steps are 1.
As currently implemented, this transformation cannot fail and will return early if the op is already in a normalized form.
Definition at line 21 of file AffineParallelNormalize.cpp.
References mlir::OpBuilder::atBlockBegin(), mlir::AffineExpr::ceilDiv(), mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::AffineValueMap::getNumDims(), mlir::AffineMap::getNumDims(), mlir::AffineValueMap::getNumSymbols(), mlir::AffineMap::getNumSymbols(), mlir::AffineValueMap::getOperands(), mlir::AffineValueMap::getResult(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), mlir::normalizeAffineParallel(), and mlir::Value::replaceAllUsesExcept().
Referenced by normalizeAffineParallel().