MLIR: lib/Transforms/BufferPlacement.cpp File Reference
BufferPlacement.cpp File Reference
#include "mlir/Transforms/BufferPlacement.h"
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SetOperations.h"
Functions
template<typename FuncT >
static void walkReturnOperations (Region *region, const FuncT &func)
Walks over all immediate return-like terminators in the given region.
Function Documentation
walkReturnOperations()
template<typename FuncT > static void walkReturnOperations (Region * region, const FuncT & func) static
Walks over all immediate return-like terminators in the given region.
Definition at line 71 of file BufferPlacement.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Operation::emitError(), mlir::detail::enumerate(), mlir::Region::front(), mlir::SideEffects::Resource::Base< AutomaticAllocationScopeResource >::get(), mlir::BlockArgument::getArgNumber(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::SideEffects::EffectInstance< EffectT >::getEffect(), mlir::LivenessBlockInfo::getEndOperation(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::BlockArgument::getOwner(), mlir::OpResult::getOwner(), mlir::Block::getParent(), mlir::Value::getParentBlock(), mlir::Region::getParentOp(), mlir::Operation::getParentRegion(), mlir::Operation::getRegions(), mlir::SideEffects::EffectInstance< EffectT >::getResource(), mlir::LivenessBlockInfo::getStartOperation(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Operation::getUsers(), mlir::SideEffects::EffectInstance< EffectT >::getValue(), mlir::Value::isa(), mlir::Operation::isBeforeInBlock(), mlir::ShapedType::isDynamic(), mlir::Operation::moveAfter(), mlir::Operation::moveBefore(), mlir::Block::pred_begin(), mlir::Block::pred_end(), mlir::Operation::setOperand(), mlir::Block::succ_begin(), mlir::Block::succ_end(), and mlir::Operation::walk().