MLIR: lib/CAPI/IR/StandardTypes.cpp File Reference
StandardTypes.cpp File Reference
#include "mlir-c/StandardTypes.h"
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
#include "mlir/CAPI/AffineMap.h"
#include "mlir/CAPI/IR.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/StandardTypes.h"
Functions
int mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
int mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
int mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
int mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
int mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
int mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
int mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
int mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
int mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
int mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
int mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
int mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
int mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
int mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
int mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks wither the dim-th dimension of the given shaped type is dynamic.
int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
int mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
int mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
int mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
MlirType mlirVectorTypeGet (intptr_t rank, int64_t *shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensios, with the given element type in the same context as the element type.
int mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
int mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
int mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
MlirType mlirRankedTensorTypeGet (intptr_t rank, int64_t *shape, MlirType elementType)
Creates a tensor type of a fixed rank with the given shape and element type in the same context as the element type.
MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
int mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, int64_t *shape, intptr_t numMaps, MlirAffineMap *affineMaps, unsigned memorySpace)
MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, int64_t *shape, unsigned memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
intptr_t mlirMemRefTypeGetNumAffineMaps (MlirType type)
Returns the number of affine layout maps in the given MemRef type.
MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type, intptr_t pos)
Returns the pos-th affine map of the given MemRef type.
unsigned mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
int mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, unsigned memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
unsigned mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
int mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType *elements)
Creates a tuple type that consists of the given list of elemental types.
intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
Function Documentation
mlirBF16TypeGet()
MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
The type is owned by the context.
Definition at line 71 of file StandardTypes.cpp.
References mlir::FloatType::getBF16(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirComplexTypeGet()
MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 111 of file StandardTypes.cpp.
References mlir::ComplexType::get(), and unwrap().
mlirComplexTypeGetElementType()
MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
Definition at line 115 of file StandardTypes.cpp.
References getElementType(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirF16TypeGet()
MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
The type is owned by the context.
Definition at line 77 of file StandardTypes.cpp.
References mlir::FloatType::getF16(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirF32TypeGet()
MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
The type is owned by the context.
Definition at line 83 of file StandardTypes.cpp.
References mlir::FloatType::getF32(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirF64TypeGet()
MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
The type is owned by the context.
Definition at line 89 of file StandardTypes.cpp.
References mlir::FloatType::getF64(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIndexTypeGet()
MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
The type is owned by the context.
Definition at line 61 of file StandardTypes.cpp.
References mlir::IndexType::get(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeGet()
MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 27 of file StandardTypes.cpp.
References mlir::IntegerType::get(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeGetWidth()
unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
Definition at line 39 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeIsSigned()
int mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
Definition at line 47 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeIsSignless()
int mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
Definition at line 43 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeIsUnsigned()
int mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
Definition at line 51 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeSignedGet()
MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 31 of file StandardTypes.cpp.
References mlir::IntegerType::get(), mlir::IntegerType::Signed, and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeUnsignedGet()
MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 35 of file StandardTypes.cpp.
References mlir::IntegerType::get(), mlir::IntegerType::Unsigned, and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirMemRefTypeContiguousGet()
MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, int64_t * shape, unsigned memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
The type has no affine maps, i.e. represents a default row-major contiguous memref. The type is owned by the context.
Definition at line 212 of file StandardTypes.cpp.
References mlir::MemRefType::get(), and unwrap().
mlirMemRefTypeGet()
MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, int64_t * shape, intptr_t numMaps, MlirAffineMap * affineMaps, unsigned memorySpace)
Definition at line 202 of file StandardTypes.cpp.
References mlir::MemRefType::get(), unwrap(), and unwrapList().
mlirMemRefTypeGetAffineMap()
MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type, intptr_t pos)
Returns the pos-th affine map of the given MemRef type.
Definition at line 224 of file StandardTypes.cpp.
References getAffineMaps(), and unwrap().
mlirMemRefTypeGetMemorySpace()
unsigned mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
Definition at line 228 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
mlirMemRefTypeGetNumAffineMaps()
intptr_t mlirMemRefTypeGetNumAffineMaps (MlirType type)
Returns the number of affine layout maps in the given MemRef type.
Definition at line 219 of file StandardTypes.cpp.
References mlir::Type::cast(), getAffineMaps(), and unwrap().
mlirNoneTypeGet()
MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
The type is owned by the context.
Definition at line 99 of file StandardTypes.cpp.
References mlir::NoneType::get(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirRankedTensorTypeGet()
MlirType mlirRankedTensorTypeGet (intptr_t rank, int64_t * shape, MlirType elementType)
Creates a tensor type of a fixed rank with the given shape and element type in the same context as the element type.
The type is owned by the context.
Definition at line 185 of file StandardTypes.cpp.
References mlir::RankedTensorType::get(), and unwrap().
mlirShapedTypeGetDimSize()
int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
Definition at line 146 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
mlirShapedTypeGetElementType()
MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
Definition at line 125 of file StandardTypes.cpp.
References getElementType(), and unwrap().
mlirShapedTypeGetRank()
int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
Definition at line 133 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
mlirShapedTypeHasRank()
int mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
Definition at line 129 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
mlirShapedTypeHasStaticShape()
int mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
Definition at line 137 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
mlirShapedTypeIsDynamicDim()
int mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks wither the dim-th dimension of the given shaped type is dynamic.
Definition at line 141 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
mlirShapedTypeIsDynamicSize()
int mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
Definition at line 150 of file StandardTypes.cpp.
References mlir::ShapedType::isDynamic().
mlirShapedTypeIsDynamicStrideOrOffset()
int mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
Definition at line 154 of file StandardTypes.cpp.
References mlir::ShapedType::isDynamicStrideOrOffset().
mlirTupleTypeGet()
MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType * elements)
Creates a tuple type that consists of the given list of elemental types.
The type is owned by the context.
Definition at line 250 of file StandardTypes.cpp.
References mlir::TupleType::get(), unwrap(), and unwrapList().
Referenced by mlir::python::PyType::operator==().
mlirTupleTypeGetNumTypes()
intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
Definition at line 257 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTupleTypeGetType()
MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
Definition at line 261 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsABF16()
int mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
Definition at line 69 of file StandardTypes.cpp.
References mlir::Type::isBF16(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAComplex()
int mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
Definition at line 107 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAF16()
int mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
Definition at line 75 of file StandardTypes.cpp.
References mlir::Type::isF16(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAF32()
int mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
Definition at line 81 of file StandardTypes.cpp.
References mlir::Type::isF32(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAF64()
int mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
Definition at line 87 of file StandardTypes.cpp.
References mlir::Type::isF64(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAIndex()
int mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
Definition at line 59 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAInteger()
int mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
Definition at line 23 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAMemRef()
int mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
Definition at line 200 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
mlirTypeIsANone()
int mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
Definition at line 97 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsARankedTensor()
int mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
Definition at line 177 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
mlirTypeIsAShaped()
int mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
Definition at line 123 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
mlirTypeIsATensor()
int mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
Definition at line 175 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
mlirTypeIsATuple()
int mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
Definition at line 248 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAUnrankedMemRef()
int mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
Definition at line 232 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
mlirTypeIsAUnrankedTensor()
int mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
Definition at line 181 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
mlirTypeIsAVector()
int mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
Definition at line 162 of file StandardTypes.cpp.
References mlir::Type::isa(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirUnrankedMemrefGetMemorySpace()
unsigned mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
Definition at line 240 of file StandardTypes.cpp.
References mlir::Type::cast(), and unwrap().
mlirUnrankedMemRefTypeGet()
MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, unsigned memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
The type is owned by the context of element type.
Definition at line 236 of file StandardTypes.cpp.
References mlir::UnrankedMemRefType::get(), and unwrap().
mlirUnrankedTensorTypeGet()
MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 192 of file StandardTypes.cpp.
References mlir::UnrankedTensorType::get(), and unwrap().
mlirVectorTypeGet()
MlirType mlirVectorTypeGet (intptr_t rank, int64_t * shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensios, with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 164 of file StandardTypes.cpp.
References mlir::VectorType::get(), and unwrap().