MLIR: mlir::BufferAssignmentCallOpConverter Class Reference
mlir::BufferAssignmentCallOpConverter Class Reference
Rewrites the CallOp to match its operands and results with the signature of the callee after rewriting the callee with BufferAssignmentFuncOpConverter.
#include "mlir/Transforms/BufferPlacement.h"
Public Member Functions
LogicalResult matchAndRewrite (CallOp, ArrayRef< Value >, ConversionPatternRewriter &) const
Performs the actual rewriting step.
Public Member Functions inherited from mlir::BufferAssignmentOpConversionPattern< CallOp >
BufferAssignmentOpConversionPattern (MLIRContext *context, BufferAssignmentPlacer *bufferAssignment=nullptr, BufferAssignmentTypeConverter *converter=nullptr, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::OpConversionPattern< CallOp >
OpConversionPattern (MLIRContext *context, PatternBenefit benefit=1)
OpConversionPattern (TypeConverter &typeConverter, MLIRContext *context, PatternBenefit benefit=1)
void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Wrappers around the ConversionPattern methods that pass the derived op type.
virtual void rewrite (CallOp op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const final
Hook for derived classes to implement combined matching and rewriting.
Public Member Functions inherited from mlir::ConversionPattern
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Public Member Functions inherited from mlir::RewritePattern
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
LogicalResult match (Operation *op) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Additional Inherited Members
Protected Member Functions inherited from mlir::ConversionPattern
ConversionPattern (StringRef rootName, PatternBenefit benefit, TypeConverter &typeConverter, MLIRContext *ctx)
Construct a conversion pattern that matches an operation with the given root name.
ConversionPattern (PatternBenefit benefit, TypeConverter &typeConverter, MatchAnyOpTypeTag tag)
Construct a conversion pattern that matches any operation type.
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes inherited from mlir::BufferAssignmentOpConversionPattern< CallOp >
BufferAssignmentPlacer * bufferAssignment
BufferAssignmentTypeConverter * converter
Protected Attributes inherited from mlir::ConversionPattern
TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Rewrites the CallOp to match its operands and results with the signature of the callee after rewriting the callee with BufferAssignmentFuncOpConverter.
Definition at line 269 of file BufferPlacement.h.
Member Function Documentation
matchAndRewrite()
LogicalResult BufferAssignmentCallOpConverter::matchAndRewrite (CallOp callOp, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const virtual
Performs the actual rewriting step.
Add an available value to the mapping.
Add the index of unavailble result value to the mapping.
This method returns the mapping values list. The unknown result values that only their indicies are available are replaced with their values.
Keeping the inserting order of mapping values.
Containing the mapping values with their inserting orders.
Containing the indices of result values with their inserting orders.
Reimplemented from mlir::OpConversionPattern< CallOp >.
Definition at line 803 of file BufferPlacement.cpp.
References mlir::PatternRewriter::create(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::BufferAssignmentTypeConverter::KeepAsFunctionResult, mlir::ConversionPatternRewriter::replaceOp(), mlir::OpBuilder::restoreInsertionPoint(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Transforms/BufferPlacement.h
lib/Transforms/BufferPlacement.cpp