MLIR: mlir::python::PyBlock Class Reference
mlir::python::PyBlock Class Reference
Wrapper around an MlirBlock.
#include "Bindings/Python/IRModules.h"
Public Member Functions
PyBlock (MlirContext context, MlirBlock block, bool detached)
PyBlock (PyBlock &&other)
~PyBlock ()
void attachToParent ()
Public Attributes
MlirContext context
MlirBlock block
Detailed Description
Wrapper around an MlirBlock.
Note that blocks can exist in a detached state (where this instance is responsible for clearing) or an attached state (where its owner is responsible).
This python wrapper retains a redundant reference to its creating context in order to facilitate checking that parts of the operation hierarchy are only assembled from the same context.
Definition at line 96 of file IRModules.h.
Constructor & Destructor Documentation
PyBlock() [1/2]
mlir::python::PyBlock::PyBlock (MlirContext context, MlirBlock block, bool detached) inline
Definition at line 98 of file IRModules.h.
PyBlock() [2/2]
mlir::python::PyBlock::PyBlock (PyBlock && other) inline
Definition at line 100 of file IRModules.h.
~PyBlock()
mlir::python::PyBlock::~PyBlock () inline
Definition at line 104 of file IRModules.h.
References mlirBlockDestroy().
Member Function Documentation
attachToParent()
void PyBlock::attachToParent ()
Definition at line 184 of file IRModules.cpp.
References mlir::python::SetPyError().
Referenced by mlir::python::PyType::operator==().
Member Data Documentation
block
MlirBlock mlir::python::PyBlock::block
Definition at line 115 of file IRModules.h.
Referenced by mlir::python::PyType::operator==().
context
MlirContext mlir::python::PyBlock::context
Definition at line 114 of file IRModules.h.
Referenced by mlir::python::PyType::operator==().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModules.h
lib/Bindings/Python/IRModules.cpp