MLIR: lib/Conversion/GPUCommon/ConvertLaunchFuncToRuntimeCalls.cpp File Reference
ConvertLaunchFuncToRuntimeCalls.cpp File Reference
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
#include "../PassDetail.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static bool isLLVMType (Value value)
Variables
static constexpr const char * kGpuBinaryStorageSuffix = "_gpubin_cst"
Function Documentation
isLLVMType()
static bool isLLVMType (Value value) static
Definition at line 216 of file ConvertLaunchFuncToRuntimeCalls.cpp.
References mlir::Location::cast(), mlir::PatternRewriter::create(), mlir::OpBuilder::create(), mlir::LLVM::createGlobalString(), mlir::LLVM::LLVMType::createStructTy(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), getElementType(), mlir::Builder::getI32IntegerAttr(), mlir::Operation::getLoc(), mlir::Operation::getOperands(), mlir::Value::getType(), mlir::Type::isa(), kGpuBinaryStorageSuffix, mlir::ConversionPatternRewriter::notifyMatchFailure(), and mlir::success().
Variable Documentation
kGpuBinaryStorageSuffix
constexpr const char* kGpuBinaryStorageSuffix = "_gpubin_cst" static
Definition at line 38 of file ConvertLaunchFuncToRuntimeCalls.cpp.
Referenced by isLLVMType().