MLIR: lib/Dialect/Affine/Transforms/LoopTiling.cpp File Reference
LoopTiling.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "affine-loop-tile"
Functions
static void moveLoopBody (AffineForOp src, AffineForOp dest, Block::iterator loc)
static void moveLoopBody (AffineForOp src, AffineForOp dest)
static void constructTiledIndexSetHyperRect (MutableArrayRef< AffineForOp > origLoops, MutableArrayRef< AffineForOp > newLoops, ArrayRef< unsigned > tileSizes)
Constructs and sets new loop bounds after tiling for the case of hyper-rectangular index sets, where the bounds of one dimension do not depend on other dimensions.
static LogicalResult checkTilingLegality (MutableArrayRef< mlir::AffineForOp > origLoops, ArrayRef< unsigned > tileSizes)
This function checks whether hyper-rectangular loop tiling of the nest represented by origLoops is valid.
static void getTileableBands (FuncOp f, std::vector< SmallVector< AffineForOp, 6 >> *bands)
static void adjustToDivisorsOfTripCounts (ArrayRef< AffineForOp > band, SmallVectorImpl< unsigned > *tileSizes)
Reduces each tile size to the largest divisor of the corresponding trip count (if the trip count is known).
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-loop-tile"
Definition at line 29 of file LoopTiling.cpp.
Function Documentation
adjustToDivisorsOfTripCounts()
static void adjustToDivisorsOfTripCounts (ArrayRef< AffineForOp > band, SmallVectorImpl< unsigned > * tileSizes) static
Reduces each tile size to the largest divisor of the corresponding trip count (if the trip count is known).
Definition at line 339 of file LoopTiling.cpp.
References diag(), mlir::failed(), mlir::getConstantTripCount(), mlir::getMemoryFootprintBytes(), getTileableBands(), mlir::separateFullTiles(), and mlir::tilePerfectlyNested().
checkTilingLegality()
static LogicalResult checkTilingLegality (MutableArrayRef< mlir::AffineForOp > origLoops, ArrayRef< unsigned > tileSizes) static
This function checks whether hyper-rectangular loop tiling of the nest represented by origLoops is valid.
The validity condition is from Irigoin and Triolet, which states that two tiles cannot depend on each other. We simplify such condition to just checking whether there is any negative dependence direction, since we have the prior knowledge that the tiling results will be hyper-rectangles, which are scheduled in the lexicographically increasing order on the vector of loop indices. This function will return failure when any dependence component is negative along any of origLoops.
Definition at line 170 of file LoopTiling.cpp.
References mlir::checkMemrefAccessDependence(), mlir::Operation::dump(), mlir::failure(), mlir::hasDependence(), mlir::DependenceComponent::lb, mlir::MemRefAccess::opInst, mlir::FlatAffineConstraints::reset(), mlir::success(), and mlir::DependenceComponent::ub.
Referenced by mlir::tilePerfectlyNested().
constructTiledIndexSetHyperRect()
static void constructTiledIndexSetHyperRect (MutableArrayRef< AffineForOp > origLoops, MutableArrayRef< AffineForOp > newLoops, ArrayRef< unsigned > tileSizes) static
Constructs and sets new loop bounds after tiling for the case of hyper-rectangular index sets, where the bounds of one dimension do not depend on other dimensions.
Bounds of each dimension can thus be treated independently, and deriving the new bounds is much simpler and faster than for the case of tiling arbitrary polyhedral shapes.
Definition at line 85 of file LoopTiling.cpp.
References mlir::AffineMap::get(), mlir::getConstantTripCount(), and mlir::getLargestDivisorOfTripCount().
Referenced by mlir::tilePerfectlyNested().
getTileableBands()
static void getTileableBands (FuncOp f, std::vector< SmallVector< AffineForOp, 6 >> * bands) static
Definition at line 321 of file LoopTiling.cpp.
References mlir::getPerfectlyNestedLoops().
Referenced by adjustToDivisorsOfTripCounts().
moveLoopBody() [1/2]
static void moveLoopBody (AffineForOp src, AffineForOp dest, Block::iterator loc) inline static
Definition at line 66 of file LoopTiling.cpp.
Referenced by moveLoopBody(), and mlir::tilePerfectlyNested().
moveLoopBody() [2/2]
static void moveLoopBody (AffineForOp src, AffineForOp dest) inline static
Definition at line 75 of file LoopTiling.cpp.
References moveLoopBody().