MLIR: lib/Dialect/OpenACC/IR/OpenACC.cpp File Reference
OpenACC.cpp File Reference
#include "mlir/Dialect/OpenACC/OpenACC.h"
#include "mlir/Dialect/OpenACC/OpenACCOpsEnums.cpp.inc"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Dialect/OpenACC/OpenACCOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
template<typename StructureOp >
static ParseResult parseRegions (OpAsmParser &parser, OperationState &state, unsigned nRegions=1)
static ParseResult parseOperandList (OpAsmParser &parser, StringRef keyword, SmallVectorImpl< OpAsmParser::OperandType > &args, SmallVectorImpl< Type > &argTypes, OperationState &result)
static void printOperandList (Operation::operand_range operands, StringRef listName, OpAsmPrinter &printer)
static ParseResult parseOptionalOperand (OpAsmParser &parser, StringRef keyword, OpAsmParser::OperandType &operand, Type type, bool &hasOptional, OperationState &result)
static ParseResult parseParallelOp (OpAsmParser &parser, OperationState &result)
Parse acc.parallel operation operation := acc.parallel async (index)? wait (index-list)? num_gangs (value)? num_workers (value)? vector_length (value)? if (value)? self (value)? reduction (value-list)? copy (value-list)? copyin (value-list)? copyout (value-list)? create (value-list)? no_create (value-list)? present (value-list)? deviceptr (value-list)? attach (value-list)? private (value-list)? firstprivate (value-list)? region attr-dict?
static void print (OpAsmPrinter &printer, ParallelOp &op)
static ParseResult parseDataOp (OpAsmParser &parser, OperationState &result)
Parse acc.data operation operation := acc.parallel present (value-list)? copy (value-list)? copyin (value-list)? copyout (value-list)? create (value-list)? no_create (value-list)? delete (value-list)? attach (value-list)? detach (value-list)? region attr-dict?
static void print (OpAsmPrinter &printer, DataOp &op)
static ParseResult parseLoopOp (OpAsmParser &parser, OperationState &result)
Parse acc.loop operation operation := acc.loop gang? vector? worker? private (value-list)? reduction (value-list)? region attr-dict?
static void print (OpAsmPrinter &printer, LoopOp &op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 659 of file OpenACC.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseDataOp()
static ParseResult parseDataOp (OpAsmParser & parser, OperationState & result) static
Parse acc.data operation operation := acc.parallel present (value-list)? copy (value-list)? copyin (value-list)? copyout (value-list)? create (value-list)? no_create (value-list)? delete (value-list)? attach (value-list)? detach (value-list)? region attr-dict?
Definition at line 361 of file OpenACC.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), and mlir::success().
parseLoopOp()
static ParseResult parseLoopOp (OpAsmParser & parser, OperationState & result) static
Parse acc.loop operation operation := acc.loop gang? vector? worker? private (value-list)? reduction (value-list)? region attr-dict?
Definition at line 483 of file OpenACC.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::acc::GANG, mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getI64Type(), mlir::OperationState::operands, mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseOperand(), parseOperandList(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), mlir::success(), mlir::OperationState::types, mlir::acc::VECTOR, and mlir::acc::WORKER.
parseOperandList()
static ParseResult parseOperandList (OpAsmParser & parser, StringRef keyword, SmallVectorImpl< OpAsmParser::OperandType > & args, SmallVectorImpl< Type > & argTypes, OperationState & result) static
Definition at line 46 of file OpenACC.cpp.
References mlir::failed(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRegionArgument(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
Referenced by parseDataOp(), parseLoopOp(), mlir::OpAsmParser::parseOperandList(), parseParallelOp(), and mlir::detail::Parser::parseToken().
parseOptionalOperand()
static ParseResult parseOptionalOperand (OpAsmParser & parser, StringRef keyword, OpAsmParser::OperandType & operand, Type type, bool & hasOptional, OperationState & result) static
Definition at line 89 of file OpenACC.cpp.
References mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), and mlir::success().
Referenced by parseParallelOp(), and mlir::detail::Parser::parseToken().
parseParallelOp()
static ParseResult parseParallelOp (OpAsmParser & parser, OperationState & result) static
Parse acc.parallel operation operation := acc.parallel async (index)? wait (index-list)? num_gangs (value)? num_workers (value)? vector_length (value)? if (value)? self (value)? reduction (value-list)? copy (value-list)? copyin (value-list)? copyout (value-list)? create (value-list)? no_create (value-list)? present (value-list)? deviceptr (value-list)? attach (value-list)? private (value-list)? firstprivate (value-list)? region attr-dict?
Definition at line 128 of file OpenACC.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI1Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), parseOptionalOperand(), and mlir::success().
parseRegions()
template<typename StructureOp > static ParseResult parseRegions (OpAsmParser & parser, OperationState & state, unsigned nRegions = 1) static
Definition at line 30 of file OpenACC.cpp.
References mlir::OperationState::addRegion(), mlir::failure(), mlir::OpAsmParser::parseRegion(), and mlir::success().
print() [1/3]
static void print (OpAsmPrinter & printer, ParallelOp & op) static
Definition at line 268 of file OpenACC.cpp.
References printOperandList(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), and mlir::OpAsmPrinter::printRegion().
print() [2/3]
static void print (OpAsmPrinter & printer, DataOp & op) static
Definition at line 436 of file OpenACC.cpp.
References printOperandList(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), and mlir::OpAsmPrinter::printRegion().
print() [3/3]
static void print (OpAsmPrinter & printer, LoopOp & op) static
Definition at line 592 of file OpenACC.cpp.
References mlir::acc::GANG, printOperandList(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), mlir::acc::VECTOR, and mlir::acc::WORKER.
printOperandList()
static void printOperandList (Operation::operand_range operands, StringRef listName, OpAsmPrinter & printer) static
Definition at line 77 of file OpenACC.cpp.
References mlir::Value::getType().
Referenced by print().