MLIR: lib/Pass/PassTiming.cpp File Reference
PassTiming.cpp File Reference
#include "PassDetail.h"
#include "mlir/Pass/PassManager.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Threading.h"
#include <chrono>
Enumerations
enum TimerKind
An enumeration of the different types of timers.
Functions
static void printTimerHeader (raw_ostream &os, TimeRecord total)
Utility to print the timer heading information.
static void printTimeEntry (raw_ostream &os, unsigned indent, StringRef name, TimeRecord time, TimeRecord totalTime)
Utility to print a single line entry in the timer output.
Variables
constexpr StringLiteral kPassTimingDescription
Enumeration Type Documentation
TimerKind
enum TimerKind strong
An enumeration of the different types of timers.
Definition at line 50 of file PassTiming.cpp.
Function Documentation
printTimeEntry()
static void printTimeEntry (raw_ostream & os, unsigned indent, StringRef name, TimeRecord time, TimeRecord totalTime) static
Utility to print a single line entry in the timer output.
Definition at line 341 of file PassTiming.cpp.
References mlir::List, mlir::Pipeline, print(), printResultsAsList(), printResultsAsPipeline(), and printTimerHeader().
Referenced by mlir::PassManager::PassTimingConfig::printTiming().
printTimerHeader()
static void printTimerHeader (raw_ostream & os, TimeRecord total) static
Utility to print the timer heading information.
Definition at line 326 of file PassTiming.cpp.
References kPassTimingDescription.
Referenced by printTimeEntry().
Variable Documentation
kPassTimingDescription
constexpr StringLiteral kPassTimingDescription
Initial value:
=
    "... Pass execution timing report ..."
Definition at line 23 of file PassTiming.cpp.
Referenced by printTimerHeader().