MLIR: lib/Dialect/PDL/IR/PDL.cpp File Reference
PDL.cpp File Reference
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "llvm/ADT/StringSwitch.h"
#include "mlir/Dialect/PDL/IR/PDLOps.cpp.inc"
Namespaces
mlir
mlir::pdl
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static LogicalResult verifyHasBindingUseInMatcher (Operation *op, StringRef bindableContextStr="`pdl.operation`")
Returns true if the given operation is used by a "binding" pdl operation within the main matcher body of a pdl.pattern.
static LogicalResult verify (ApplyConstraintOp op)
static LogicalResult verify (AttributeOp op)
static LogicalResult verify (InputOp op)
static ParseResult parseOperationOp (OpAsmParser &p, OperationState &state)
static void print (OpAsmPrinter &p, OperationOp op)
static LogicalResult verifyResultTypesAreInferrable (OperationOp op, ResultRange opResults, OperandRange resultTypes)
Verifies that the result types of this operation, defined within a pdl.rewrite, can be inferred.
static LogicalResult verify (OperationOp op)
static LogicalResult verify (PatternOp pattern)
static LogicalResult verify (ReplaceOp op)
static LogicalResult verify (RewriteOp op)
static LogicalResult verify (TypeOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 460 of file PDL.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseOperationOp()
static ParseResult parseOperationOp (OpAsmParser & p, OperationState & state) static
Definition at line 120 of file PDL.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::Builder::getArrayAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getType(), mlir::OptionalParseResult::hasValue(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalArrow(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalAttribute(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalLBrace(), mlir::OpAsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseRBrace(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), mlir::success(), and mlir::OperationState::types.
print()
static void print (OpAsmPrinter & p, OperationOp op) static
Definition at line 190 of file PDL.cpp.
References mlir::ArrayAttr::empty(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::ArrayAttr::size().
verify() [1/8]
static LogicalResult verify (ApplyConstraintOp op) static
Definition at line 86 of file PDL.cpp.
References mlir::success().
verify() [2/8]
static LogicalResult verify (AttributeOp op) static
Definition at line 96 of file PDL.cpp.
References verifyHasBindingUseInMatcher().
verify() [3/8]
static LogicalResult verify (InputOp op) static
Definition at line 112 of file PDL.cpp.
References verifyHasBindingUseInMatcher().
verify() [4/8]
static LogicalResult verify (OperationOp op) static
Definition at line 275 of file PDL.cpp.
References mlir::failed(), mlir::failure(), mlir::OperationName::getAbstractOperation(), mlir::ArrayAttr::size(), verifyHasBindingUseInMatcher(), and verifyResultTypesAreInferrable().
verify() [5/8]
static LogicalResult verify (PatternOp pattern) static
Definition at line 324 of file PDL.cpp.
References mlir::OperationState::addRegion(), mlir::WalkResult::advance(), mlir::InFlightDiagnostic::attachNote(), mlir::OpBuilder::createBlock(), mlir::Operation::emitOpError(), mlir::failure(), mlir::Region::front(), mlir::Operation::getDialect(), mlir::Builder::getI16IntegerAttr(), mlir::Operation::getLoc(), mlir::Builder::getStringAttr(), mlir::Block::getTerminator(), mlir::WalkResult::interrupt(), mlir::Region::walk(), and mlir::WalkResult::wasInterrupted().
verify() [6/8]
static LogicalResult verify (ReplaceOp op) static
Definition at line 374 of file PDL.cpp.
References mlir::success().
verify() [7/8]
static LogicalResult verify (RewriteOp op) static
Definition at line 413 of file PDL.cpp.
References mlir::Region::empty(), and mlir::success().
verify() [8/8]
static LogicalResult verify (TypeOp op) static
Definition at line 448 of file PDL.cpp.
References verifyHasBindingUseInMatcher().
verifyHasBindingUseInMatcher()
static LogicalResult verifyHasBindingUseInMatcher (Operation * op, StringRef bindableContextStr = "`pdl.operation`") static
Returns true if the given operation is used by a "binding" pdl operation within the main matcher body of a pdl.pattern.
Definition at line 65 of file PDL.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getBlock(), mlir::Operation::getParentOp(), mlir::Operation::getUsers(), and mlir::success().
Referenced by verify().
verifyResultTypesAreInferrable()
static LogicalResult verifyResultTypesAreInferrable (OperationOp op, ResultRange opResults, OperandRange resultTypes) static
Verifies that the result types of this operation, defined within a pdl.rewrite, can be inferred.
Definition at line 218 of file PDL.cpp.
References mlir::Operation::getBlock(), mlir::Operation::isBeforeInBlock(), and mlir::success().
Referenced by verify().