MLIR: lib/Conversion/StandardToLLVM/StandardToLLVM.cpp File Reference
StandardToLLVM.cpp File Reference
#include "../PassDetail.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FormatVariadic.h"
#include <functional>
Macros
#define PASS_NAME "convert-std-to-llvm"
Functions
static LLVM::LLVMType unwrap (Type type)
static Type convertMemRefTypeToBarePtr (LLVMTypeConverter &converter, MemRefType type)
Convert a MemRef type to a bare pointer to the MemRef element type.
static Value createIndexAttrConstant (OpBuilder &builder, Location loc, Type resultType, int64_t value)
static void filterFuncAttributes (ArrayRef< NamedAttribute > attrs, bool filterArgAttrs, SmallVectorImpl< NamedAttribute > &result)
Only retain those attributes that are not constructed by LLVMFuncOp::build.
static void wrapForExternalCallers (OpBuilder &rewriter, Location loc, LLVMTypeConverter &typeConverter, FuncOp funcOp, LLVM::LLVMFuncOp newFuncOp)
Creates an auxiliary function with pointer-to-memref-descriptor-struct arguments instead of unpacked arguments.
static void wrapExternalFunction (OpBuilder &builder, Location loc, LLVMTypeConverter &typeConverter, FuncOp funcOp, LLVM::LLVMFuncOp newFuncOp)
Creates an auxiliary function with pointer-to-memref-descriptor-struct arguments instead of unpacked arguments.
static NDVectorTypeInfo extractNDVectorTypeInfo (VectorType vectorType, LLVMTypeConverter &converter)
static SmallVector< int64_t, 4 > getCoordinates (ArrayRef< int64_t > basis, unsigned linearIndex)
template<typename Lambda >
void nDVectorIterate (const NDVectorTypeInfo &info, OpBuilder &builder, Lambda fun)
static LogicalResult handleMultidimensionalVectors (Operation *op, ValueRange operands, LLVMTypeConverter &typeConverter, std::function< Value(LLVM::LLVMType, ValueRange)> createOperand, ConversionPatternRewriter &rewriter)
static Optional< LLVM::AtomicBinOp > matchSimpleAtomicOp (AtomicRMWOp atomicOp)
Try to match the kind of a std.atomic_rmw to determine whether to use a lowering to llvm.atomicrmw or fallback to llvm.cmpxchg.
Variables
static constexpr unsigned kRealPosInComplexNumberStruct = 0
static constexpr unsigned kImaginaryPosInComplexNumberStruct = 1
static constexpr unsigned kAllocatedPtrPosInMemRefDescriptor = 0
static constexpr unsigned kAlignedPtrPosInMemRefDescriptor = 1
static constexpr unsigned kOffsetPosInMemRefDescriptor = 2
static constexpr unsigned kSizePosInMemRefDescriptor = 3
static constexpr unsigned kStridePosInMemRefDescriptor = 4
static constexpr unsigned kRankInUnrankedMemRefDescriptor = 0
static constexpr unsigned kPtrInUnrankedMemRefDescriptor = 1
Macro Definition Documentation
PASS_NAME
#define PASS_NAME "convert-std-to-llvm"
Definition at line 41 of file StandardToLLVM.cpp.
Function Documentation
convertMemRefTypeToBarePtr()
static Type convertMemRefTypeToBarePtr (LLVMTypeConverter & converter, MemRefType type) static
Convert a MemRef type to a bare pointer to the MemRef element type.
Definition at line 84 of file StandardToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::failed(), mlir::MemRefType::getMemorySpace(), mlir::LLVM::LLVMType::getPointerTo(), mlir::getStridesAndOffset(), and unwrap().
Referenced by mlir::barePtrFuncArgTypeConverter().
createIndexAttrConstant()
static Value createIndexAttrConstant (OpBuilder & builder, Location loc, Type resultType, int64_t value) static
Definition at line 552 of file StandardToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), and mlir::StructBuilder::value.
Referenced by mlir::UnrankedMemRefDescriptor::computeSizes(), mlir::ConvertToLLVMPattern::createIndexConstant(), mlir::MemRefDescriptor::setConstantOffset(), mlir::MemRefDescriptor::setConstantSize(), mlir::MemRefDescriptor::setConstantStride(), mlir::MemRefDescriptor::size(), and mlir::LLVM::detail::vectorOneToOneRewrite().
extractNDVectorTypeInfo()
static NDVectorTypeInfo extractNDVectorTypeInfo (VectorType vectorType, LLVMTypeConverter & converter) static
Definition at line 1250 of file StandardToLLVM.cpp.
References mlir::TypeConverter::convertType(), and mlir::LLVM::LLVMType::getArrayElementType().
Referenced by handleMultidimensionalVectors(), and mlir::LLVM::detail::vectorOneToOneRewrite().
filterFuncAttributes()
static void filterFuncAttributes (ArrayRef< NamedAttribute > attrs, bool filterArgAttrs, SmallVectorImpl< NamedAttribute > & result) static
Only retain those attributes that are not constructed by LLVMFuncOp::build.
If filterArgAttrs is set, also filter out argument attributes.
Definition at line 958 of file StandardToLLVM.cpp.
References mlir::SymbolTable::getSymbolAttrName(), mlir::impl::getTypeAttrName(), and mlir::impl::isArgAttrName().
Referenced by wrapExternalFunction(), and wrapForExternalCallers().
getCoordinates()
static SmallVector<int64_t, 4> getCoordinates (ArrayRef< int64_t > basis, unsigned linearIndex) static
Definition at line 1277 of file StandardToLLVM.cpp.
Referenced by nDVectorIterate().
handleMultidimensionalVectors()
static LogicalResult handleMultidimensionalVectors (Operation * op, ValueRange operands, LLVMTypeConverter & typeConverter, std::function< Value(LLVM::LLVMType, ValueRange)> createOperand, ConversionPatternRewriter & rewriter) static
Definition at line 1351 of file StandardToLLVM.cpp.
References mlir::PatternRewriter::create(), mlir::Type::dyn_cast(), extractNDVectorTypeInfo(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::ValueRange::getType(), nDVectorIterate(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
Referenced by mlir::LLVM::detail::vectorOneToOneRewrite().
matchSimpleAtomicOp()
static Optional<LLVM::AtomicBinOp> matchSimpleAtomicOp (AtomicRMWOp atomicOp) static
Try to match the kind of a std.atomic_rmw to determine whether to use a lowering to llvm.atomicrmw or fallback to llvm.cmpxchg.
Definition at line 3098 of file StandardToLLVM.cpp.
References mlir::Block::back(), mlir::OpBuilder::clone(), mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::OpBuilder::createBlock(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::Block::front(), mlir::Builder::getContext(), mlir::Builder::getI64ArrayAttr(), mlir::OpBuilder::getInsertionBlock(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::Operation::getLoc(), mlir::Operation::getOperand(), mlir::Operation::getResults(), mlir::LLVM::LLVMType::getStructTy(), mlir::Block::getTerminator(), mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::map(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and mlir::Block::without_terminator().
nDVectorIterate()
template<typename Lambda > void nDVectorIterate (const NDVectorTypeInfo & info, OpBuilder & builder, Lambda fun)
Definition at line 1294 of file StandardToLLVM.cpp.
References getCoordinates(), and mlir::Builder::getI64ArrayAttr().
Referenced by handleMultidimensionalVectors(), and mlir::LLVM::detail::vectorOneToOneRewrite().
unwrap()
static LLVM::LLVMType unwrap (Type type) static
Definition at line 44 of file StandardToLLVM.cpp.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::UnknownLoc::get(), and mlir::Type::getContext().
Referenced by llvm::GraphTraits< const mlir::CallGraphNode * >::child_begin(), llvm::GraphTraits< const mlir::CallGraphNode * >::child_end(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), convertMemRefTypeToBarePtr(), getDenseAttribute(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetValue(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirArrayAttrGetNumElements(), mlirAttributeDump(), mlirAttributeEqual(), mlirAttributeIsAAffineMap(), mlirAttributeIsAArray(), mlirAttributeIsABool(), mlirAttributeIsADenseElements(), mlirAttributeIsADenseFPElements(), mlirAttributeIsADenseIntElements(), mlirAttributeIsADictionary(), mlirAttributeIsAElements(), mlirAttributeIsAFlatSymbolRef(), mlirAttributeIsAFloat(), mlirAttributeIsAInteger(), mlirAttributeIsAIntegerSet(), mlirAttributeIsAOpaque(), mlirAttributeIsAOpaqueElements(), mlirAttributeIsASparseElements(), mlirAttributeIsAString(), mlirAttributeIsASymbolRef(), mlirAttributeIsAType(), mlirAttributeIsAUnit(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBF16TypeGet(), mlirBlockAppendOwnedOperation(), mlirBlockCreate(), mlirBlockDestroy(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockGetNumArguments(), mlirBlockInsertOwnedOperation(), mlirBlockIsNull(), mlirBlockPrint(), mlirBoolAttrGet(), mlirBoolAttrGetValue(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirContextDestroy(), mlirContextEqual(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetBoolSplatValue(), mlirDenseElementsAttrGetBoolValue(), mlirDenseElementsAttrGetDoubleSplatValue(), mlirDenseElementsAttrGetDoubleValue(), mlirDenseElementsAttrGetFloatSplatValue(), mlirDenseElementsAttrGetFloatValue(), mlirDenseElementsAttrGetInt32SplatValue(), mlirDenseElementsAttrGetInt32Value(), mlirDenseElementsAttrGetInt64SplatValue(), mlirDenseElementsAttrGetInt64Value(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrGetUInt32SplatValue(), mlirDenseElementsAttrGetUInt32Value(), mlirDenseElementsAttrGetUInt64SplatValue(), mlirDenseElementsAttrGetUInt64Value(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrIsSplat(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirDictionaryAttrGetNumElements(), mlirElementsAttrGetNumElements(), mlirElementsAttrGetValue(), mlirElementsAttrIsValidIndex(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFlatSymbolRefAttrGet(), mlirFloatAttrDoubleGet(), mlirFloatAttrGetValueDouble(), mlirFloatSymbolRefAttrGetValue(), mlirIndexTypeGet(), mlirIntegerAttrGet(), mlirIntegerAttrGetValueInt(), mlirIntegerTypeGet(), mlirIntegerTypeGetWidth(), mlirIntegerTypeIsSigned(), mlirIntegerTypeIsSignless(), mlirIntegerTypeIsUnsigned(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLocationFileLineColGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetMemorySpace(), mlirMemRefTypeGetNumAffineMaps(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleDestroy(), mlirModuleGetOperation(), mlirNoneTypeGet(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOpaqueAttrGetDialectNamespace(), mlirOperationCreate(), mlirOperationDestroy(), mlirOperationDump(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetNextInBlock(), mlirOperationGetNumAttributes(), mlirOperationGetNumOperands(), mlirOperationGetNumRegions(), mlirOperationGetNumResults(), mlirOperationGetNumSuccessors(), mlirOperationGetOperand(), mlirOperationGetRegion(), mlirOperationGetResult(), mlirOperationGetSuccessor(), mlirOperationIsNull(), mlirOperationPrint(), mlirRankedTensorTypeGet(), mlirRegionAppendOwnedBlock(), mlirRegionGetFirstBlock(), mlirRegionInsertOwnedBlock(), mlirRegionIsNull(), mlirRegisterAllDialects(), mlirShapedTypeGetDimSize(), mlirShapedTypeGetElementType(), mlirShapedTypeGetRank(), mlirShapedTypeHasRank(), mlirShapedTypeHasStaticShape(), mlirShapedTypeIsDynamicDim(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetNumNestedReferences(), mlirSymbolRefAttrGetRootReference(), mlirTupleTypeGet(), mlirTupleTypeGetNumTypes(), mlirTupleTypeGetType(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeDump(), mlirTypeEqual(), mlirTypeGetContext(), mlirTypeIsABF16(), mlirTypeIsAComplex(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), mlirTypeIsAIndex(), mlirTypeIsAInteger(), mlirTypeIsAMemRef(), mlirTypeIsANone(), mlirTypeIsARankedTensor(), mlirTypeIsAShaped(), mlirTypeIsATensor(), mlirTypeIsATuple(), mlirTypeIsAUnrankedMemRef(), mlirTypeIsAUnrankedTensor(), mlirTypeIsAVector(), mlirTypeParseGet(), mlirTypePrint(), mlirUnitAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGet(), mlirUnrankedTensorTypeGet(), mlirValueGetType(), mlirValuePrint(), mlirVectorTypeGet(), mlir::ValueTypeIterator< ValueIteratorT >::operator*(), mlir::Block::splitBlock(), unwrapList(), and mlir::tblgen::Operator::VariableDecoratorIterator::VariableDecoratorIterator().
wrapExternalFunction()
static void wrapExternalFunction (OpBuilder & builder, Location loc, LLVMTypeConverter & typeConverter, FuncOp funcOp, LLVM::LLVMFuncOp newFuncOp) static
Creates an auxiliary function with pointer-to-memref-descriptor-struct arguments instead of unpacked arguments.
Creates a body for the (external) newFuncOp that allocates a memref descriptor on stack, packs the individual arguments into this descriptor and passes a pointer to it into the auxiliary function. This auxiliary external function is now compatible with functions defined in C using pointers to C structs corresponding to a memref descriptor.
Definition at line 1016 of file StandardToLLVM.cpp.
References mlir::Block::begin(), mlir::Type::cast(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), mlir::ConversionPatternRewriter::convertRegionTypes(), mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), filterFuncAttributes(), mlir::MemRefDescriptor::fromStaticShape(), mlir::Block::front(), mlir::impl::getArgAttrDict(), mlir::impl::getArgAttrName(), mlir::Block::getArgument(), mlir::OpState::getAttrOfType(), mlir::OpState::getAttrs(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexType(), mlir::FunctionType::getInputs(), mlir::Builder::getIntegerAttr(), mlir::Operation::getLoc(), mlir::OpState::getLoc(), mlir::Builder::getNamedAttr(), mlir::FunctionType::getNumInputs(), mlir::MemRefDescriptor::getNumUnpackedValues(), mlir::UnrankedMemRefDescriptor::getNumUnpackedValues(), mlir::Value::getType(), mlir::BlockArgument::getType(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::MemRefDescriptor::pack(), mlir::UnrankedMemRefDescriptor::pack(), mlir::ConversionPatternRewriter::replaceOp(), mlir::ConversionPatternRewriter::replaceUsesOfBlockArgument(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and wrapForExternalCallers().
wrapForExternalCallers()
static void wrapForExternalCallers (OpBuilder & rewriter, Location loc, LLVMTypeConverter & typeConverter, FuncOp funcOp, LLVM::LLVMFuncOp newFuncOp) static
Creates an auxiliary function with pointer-to-memref-descriptor-struct arguments instead of unpacked arguments.
This function can be called from C by passing a pointer to a C struct corresponding to a memref descriptor. Internally, the auxiliary function unpacks the descriptor into individual components and forwards them to newFuncOp.
Definition at line 975 of file StandardToLLVM.cpp.
References mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), mlir::OpBuilder::create(), mlir::detail::enumerate(), filterFuncAttributes(), mlir::OpState::getAttrs(), mlir::OpBuilder::setInsertionPointToStart(), mlir::MemRefDescriptor::unpack(), and mlir::UnrankedMemRefDescriptor::unpack().
Referenced by wrapExternalFunction().
Variable Documentation
kAlignedPtrPosInMemRefDescriptor
constexpr unsigned kAlignedPtrPosInMemRefDescriptor = 1 static
Definition at line 357 of file StandardToLLVM.cpp.
Referenced by mlir::MemRefDescriptor::alignedPtr(), mlir::MemRefDescriptorView::alignedPtr(), mlir::MemRefDescriptor::getElementType(), mlir::MemRefDescriptor::pack(), and mlir::MemRefDescriptor::setAlignedPtr().
kAllocatedPtrPosInMemRefDescriptor
constexpr unsigned kAllocatedPtrPosInMemRefDescriptor = 0 static
Definition at line 356 of file StandardToLLVM.cpp.
Referenced by mlir::MemRefDescriptor::allocatedPtr(), mlir::MemRefDescriptorView::allocatedPtr(), mlir::MemRefDescriptor::pack(), and mlir::MemRefDescriptor::setAllocatedPtr().
kImaginaryPosInComplexNumberStruct
constexpr unsigned kImaginaryPosInComplexNumberStruct = 1 static
Definition at line 228 of file StandardToLLVM.cpp.
Referenced by mlir::ComplexStructBuilder::imaginary(), and mlir::ComplexStructBuilder::setImaginary().
kOffsetPosInMemRefDescriptor
constexpr unsigned kOffsetPosInMemRefDescriptor = 2 static
Definition at line 358 of file StandardToLLVM.cpp.
Referenced by mlir::MemRefDescriptor::MemRefDescriptor(), mlir::MemRefDescriptor::offset(), mlir::MemRefDescriptorView::offset(), mlir::MemRefDescriptor::pack(), and mlir::MemRefDescriptor::setOffset().
kPtrInUnrankedMemRefDescriptor
constexpr unsigned kPtrInUnrankedMemRefDescriptor = 1 static
Definition at line 389 of file StandardToLLVM.cpp.
Referenced by mlir::UnrankedMemRefDescriptor::memRefDescPtr(), mlir::UnrankedMemRefDescriptor::pack(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
kRankInUnrankedMemRefDescriptor
constexpr unsigned kRankInUnrankedMemRefDescriptor = 0 static
Definition at line 388 of file StandardToLLVM.cpp.
Referenced by mlir::UnrankedMemRefDescriptor::pack(), mlir::UnrankedMemRefDescriptor::rank(), and mlir::UnrankedMemRefDescriptor::setRank().
kRealPosInComplexNumberStruct
constexpr unsigned kRealPosInComplexNumberStruct = 0 static
Definition at line 227 of file StandardToLLVM.cpp.
Referenced by mlir::ComplexStructBuilder::real(), and mlir::ComplexStructBuilder::setReal().
kSizePosInMemRefDescriptor
constexpr unsigned kSizePosInMemRefDescriptor = 3 static
Definition at line 359 of file StandardToLLVM.cpp.
Referenced by mlir::MemRefDescriptor::pack(), mlir::MemRefDescriptor::setSize(), mlir::MemRefDescriptor::size(), mlir::MemRefDescriptorView::size(), and mlir::MemRefDescriptorView::stride().
kStridePosInMemRefDescriptor
constexpr unsigned kStridePosInMemRefDescriptor = 4 static
Definition at line 360 of file StandardToLLVM.cpp.
Referenced by mlir::MemRefDescriptor::setStride(), and mlir::MemRefDescriptor::stride().