MLIR: lib/CAPI/IR/StandardAttributes.cpp File Reference
StandardAttributes.cpp File Reference
#include "mlir-c/StandardAttributes.h"
#include "mlir/CAPI/AffineMap.h"
#include "mlir/CAPI/IR.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/StandardTypes.h"
Functions
int mlirAttributeIsAAffineMap (MlirAttribute attr)
Checks whether the given attribute is an affine map attribute.
MlirAttribute mlirAffineMapAttrGet (MlirAffineMap map)
Creates an affine map attribute wrapping the given map.
MlirAffineMap mlirAffineMapAttrGetValue (MlirAttribute attr)
Returns the affine map wrapped in the given affine map attribute.
int mlirAttributeIsAArray (MlirAttribute attr)
Checks whether the given attribute is an array attribute.
MlirAttribute mlirArrayAttrGet (MlirContext ctx, intptr_t numElements, MlirAttribute *elements)
Creates an array element containing the given list of elements in the given context.
intptr_t mlirArrayAttrGetNumElements (MlirAttribute attr)
Returns the number of elements stored in the given array attribute.
MlirAttribute mlirArrayAttrGetElement (MlirAttribute attr, intptr_t pos)
Returns pos-th element stored in the given array attribute.
int mlirAttributeIsADictionary (MlirAttribute attr)
Checks whether the given attribute is a dictionary attribute.
MlirAttribute mlirDictionaryAttrGet (MlirContext ctx, intptr_t numElements, MlirNamedAttribute *elements)
Creates a dictionary attribute containing the given list of elements in the provided context.
intptr_t mlirDictionaryAttrGetNumElements (MlirAttribute attr)
Returns the number of attributes contained in a dictionary attribute.
MlirNamedAttribute mlirDictionaryAttrGetElement (MlirAttribute attr, intptr_t pos)
Returns pos-th element of the given dictionary attribute.
MlirAttribute mlirDictionaryAttrGetElementByName (MlirAttribute attr, const char *name)
Returns the dictionary attribute element with the given name or NULL if the given name does not exist in the dictionary.
int mlirAttributeIsAFloat (MlirAttribute attr)
Checks whether the given attribute is a floating point attribute.
MlirAttribute mlirFloatAttrDoubleGet (MlirContext ctx, MlirType type, double value)
Creates a floating point attribute in the given context with the given double value and double-precision FP semantics.
double mlirFloatAttrGetValueDouble (MlirAttribute attr)
Returns the value stored in the given floating point attribute, interpreting the value as double.
int mlirAttributeIsAInteger (MlirAttribute attr)
Checks whether the given attribute is an integer attribute.
MlirAttribute mlirIntegerAttrGet (MlirType type, int64_t value)
Creates an integer attribute of the given type with the given integer value.
int64_t mlirIntegerAttrGetValueInt (MlirAttribute attr)
Returns the value stored in the given integer attribute, assuming the value fits into a 64-bit integer.
int mlirAttributeIsABool (MlirAttribute attr)
Checks whether the given attribute is a bool attribute.
MlirAttribute mlirBoolAttrGet (MlirContext ctx, int value)
Creates a bool attribute in the given context with the given value.
int mlirBoolAttrGetValue (MlirAttribute attr)
Returns the value stored in the given bool attribute.
int mlirAttributeIsAIntegerSet (MlirAttribute attr)
Checks whether the given attribute is an integer set attribute.
int mlirAttributeIsAOpaque (MlirAttribute attr)
Checks whether the given attribute is an opaque attribute.
MlirAttribute mlirOpaqueAttrGet (MlirContext ctx, const char *dialectNamespace, intptr_t dataLength, const char *data, MlirType type)
Creates an opaque attribute in the given context associated with the dialect identified by its namespace.
const char * mlirOpaqueAttrGetDialectNamespace (MlirAttribute attr)
Returns the namepsace of the dialect with which the given opaque attribute is associated.
void mlirOpaqueAttrGetData (MlirAttribute attr, MlirStringCallback callback, void *userData)
Calls the provided callback with the opaque byte data stored in the given opaque attribute.
int mlirAttributeIsAString (MlirAttribute attr)
Checks whether the given attribute is a string attribute.
MlirAttribute mlirStringAttrGet (MlirContext ctx, intptr_t length, const char *data)
Creates a string attribute in the given context containing the given string.
MlirAttribute mlirStringAttrTypedGet (MlirType type, intptr_t length, const char *data)
Creates a string attribute in the given context containing the given string.
void mlirStringAttrGetValue (MlirAttribute attr, MlirStringCallback callback, void *userData)
Calls the provided callback with the string stored in the given string attribute.
int mlirAttributeIsASymbolRef (MlirAttribute attr)
Checks whether the given attribute is a symbol reference attribute.
MlirAttribute mlirSymbolRefAttrGet (MlirContext ctx, intptr_t length, const char *symbol, intptr_t numReferences, MlirAttribute *references)
Creates a symbol reference attribute in the given context referencing a symbol identified by the given string inside a list of nested references.
void mlirSymbolRefAttrGetRootReference (MlirAttribute attr, MlirStringCallback callback, void *userData)
Calls the provided callback with the string containing the root referenced symbol.
void mlirSymbolRefAttrGetLeafReference (MlirAttribute attr, MlirStringCallback callback, void *userData)
Calls the provided callback with the string containing the leaf referenced symbol.
intptr_t mlirSymbolRefAttrGetNumNestedReferences (MlirAttribute attr)
Returns the number of references nested in the given symbol reference attribute.
MlirAttribute mlirSymbolRefAttrGetNestedReference (MlirAttribute attr, intptr_t pos)
Returns pos-th reference nested in the given symbol reference attribute.
int mlirAttributeIsAFlatSymbolRef (MlirAttribute attr)
Checks whether the given attribute is a flat symbol reference attribute.
MlirAttribute mlirFlatSymbolRefAttrGet (MlirContext ctx, intptr_t length, const char *symbol)
Creates a flat symbol reference attribute in the given context referencing a symbol identified by the given string.
void mlirFloatSymbolRefAttrGetValue (MlirAttribute attr, MlirStringCallback callback, void *userData)
Calls the provided callback with the string containing the referenced symbol.
int mlirAttributeIsAType (MlirAttribute attr)
Checks whether the given attribute is a type attribute.
MlirAttribute mlirTypeAttrGet (MlirType type)
Creates a type attribute wrapping the given type in the same context as the type.
MlirType mlirTypeAttrGetValue (MlirAttribute attr)
Returns the type stored in the given type attribute.
int mlirAttributeIsAUnit (MlirAttribute attr)
Checks whether the given attribute is a unit attribute.
MlirAttribute mlirUnitAttrGet (MlirContext ctx)
Creates a unit attribute in the given context.
int mlirAttributeIsAElements (MlirAttribute attr)
Checks whether the given attribute is an elements attribute.
MlirAttribute mlirElementsAttrGetValue (MlirAttribute attr, intptr_t rank, uint64_t *idxs)
Returns the element at the given rank-dimensional index.
int mlirElementsAttrIsValidIndex (MlirAttribute attr, intptr_t rank, uint64_t *idxs)
Checks whether the given rank-dimensional index is valid in the given elements attribute.
int64_t mlirElementsAttrGetNumElements (MlirAttribute attr)
Gets the total number of elements in the given elements attribute.
int mlirAttributeIsADenseElements (MlirAttribute attr)
Checks whether the given attribute is a dense elements attribute.
int mlirAttributeIsADenseIntElements (MlirAttribute attr)
int mlirAttributeIsADenseFPElements (MlirAttribute attr)
MlirAttribute mlirDenseElementsAttrGet (MlirType shapedType, intptr_t numElements, MlirAttribute *elements)
Creates a dense elements attribute with the given Shaped type and elements in the same context as the type.
MlirAttribute mlirDenseElementsAttrSplatGet (MlirType shapedType, MlirAttribute element)
Creates a dense elements attribute with the given Shaped type containing a single replicated element (splat).
MlirAttribute mlirDenseElementsAttrBoolSplatGet (MlirType shapedType, int element)
MlirAttribute mlirDenseElementsAttrUInt32SplatGet (MlirType shapedType, uint32_t element)
MlirAttribute mlirDenseElementsAttrInt32SplatGet (MlirType shapedType, int32_t element)
MlirAttribute mlirDenseElementsAttrUInt64SplatGet (MlirType shapedType, uint64_t element)
MlirAttribute mlirDenseElementsAttrInt64SplatGet (MlirType shapedType, int64_t element)
MlirAttribute mlirDenseElementsAttrFloatSplatGet (MlirType shapedType, float element)
MlirAttribute mlirDenseElementsAttrDoubleSplatGet (MlirType shapedType, double element)
MlirAttribute mlirDenseElementsAttrBoolGet (MlirType shapedType, intptr_t numElements, int *elements)
Creates a dense elements attribute with the given shaped type from elements of a specific type.
template<typename T >
static MlirAttribute getDenseAttribute (MlirType shapedType, intptr_t numElements, T *elements)
Creates a dense attribute with elements of the type deduced by templates.
MlirAttribute mlirDenseElementsAttrUInt32Get (MlirType shapedType, intptr_t numElements, uint32_t *elements)
MlirAttribute mlirDenseElementsAttrInt32Get (MlirType shapedType, intptr_t numElements, int32_t *elements)
MlirAttribute mlirDenseElementsAttrUInt64Get (MlirType shapedType, intptr_t numElements, uint64_t *elements)
MlirAttribute mlirDenseElementsAttrInt64Get (MlirType shapedType, intptr_t numElements, int64_t *elements)
MlirAttribute mlirDenseElementsAttrFloatGet (MlirType shapedType, intptr_t numElements, float *elements)
MlirAttribute mlirDenseElementsAttrDoubleGet (MlirType shapedType, intptr_t numElements, double *elements)
MlirAttribute mlirDenseElementsAttrStringGet (MlirType shapedType, intptr_t numElements, intptr_t *strLengths, const char **strs)
Creates a dense elements attribute with the given shaped type from string elements.
MlirAttribute mlirDenseElementsAttrReshapeGet (MlirAttribute attr, MlirType shapedType)
Creates a dense elements attribute that has the same data as the given dense elements attribute and a different shaped type.
int mlirDenseElementsAttrIsSplat (MlirAttribute attr)
Checks whether the given dense elements attribute contains a single replicated value (splat).
MlirAttribute mlirDenseElementsAttrGetSplatValue (MlirAttribute attr)
Returns the single replicated value (splat) of a specific type contained by the given dense elements attribute.
int mlirDenseElementsAttrGetBoolSplatValue (MlirAttribute attr)
int32_t mlirDenseElementsAttrGetInt32SplatValue (MlirAttribute attr)
uint32_t mlirDenseElementsAttrGetUInt32SplatValue (MlirAttribute attr)
int64_t mlirDenseElementsAttrGetInt64SplatValue (MlirAttribute attr)
uint64_t mlirDenseElementsAttrGetUInt64SplatValue (MlirAttribute attr)
float mlirDenseElementsAttrGetFloatSplatValue (MlirAttribute attr)
double mlirDenseElementsAttrGetDoubleSplatValue (MlirAttribute attr)
void mlirDenseElementsAttrGetStringSplatValue (MlirAttribute attr, MlirStringCallback callback, void *userData)
int mlirDenseElementsAttrGetBoolValue (MlirAttribute attr, intptr_t pos)
Returns the pos-th value (flat contiguous indexing) of a specific type contained by the given dense elements attribute.
int32_t mlirDenseElementsAttrGetInt32Value (MlirAttribute attr, intptr_t pos)
uint32_t mlirDenseElementsAttrGetUInt32Value (MlirAttribute attr, intptr_t pos)
int64_t mlirDenseElementsAttrGetInt64Value (MlirAttribute attr, intptr_t pos)
uint64_t mlirDenseElementsAttrGetUInt64Value (MlirAttribute attr, intptr_t pos)
float mlirDenseElementsAttrGetFloatValue (MlirAttribute attr, intptr_t pos)
double mlirDenseElementsAttrGetDoubleValue (MlirAttribute attr, intptr_t pos)
void mlirDenseElementsAttrGetStringValue (MlirAttribute attr, intptr_t pos, MlirStringCallback callback, void *userData)
int mlirAttributeIsAOpaqueElements (MlirAttribute attr)
Checks whether the given attribute is an opaque elements attribute.
int mlirAttributeIsASparseElements (MlirAttribute attr)
Checks whether the given attribute is a sparse elements attribute.
MlirAttribute mlirSparseElementsAttribute (MlirType shapedType, MlirAttribute denseIndices, MlirAttribute denseValues)
Creates a sparse elements attribute of the given shape from a list of indices and a list of associated values.
MlirAttribute mlirSparseElementsAttrGetIndices (MlirAttribute attr)
Returns the dense elements attribute containing 64-bit integer indices of non-null elements in the given sparse elements attribute.
MlirAttribute mlirSparseElementsAttrGetValues (MlirAttribute attr)
Returns the dense elements attribute containing the non-null elements in the given sparse elements attribute.
Function Documentation
getDenseAttribute()
template<typename T > static MlirAttribute getDenseAttribute (MlirType shapedType, intptr_t numElements, T * elements) static
Creates a dense attribute with elements of the type deduced by templates.
Definition at line 392 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
Referenced by mlirDenseElementsAttrDoubleGet(), mlirDenseElementsAttrFloatGet(), mlirDenseElementsAttrInt32Get(), mlirDenseElementsAttrInt64Get(), mlirDenseElementsAttrUInt32Get(), and mlirDenseElementsAttrUInt64Get().
mlirAffineMapAttrGet()
MlirAttribute mlirAffineMapAttrGet (MlirAffineMap map)
Creates an affine map attribute wrapping the given map.
The attribute belongs to the same context as the affine map.
Definition at line 25 of file StandardAttributes.cpp.
References mlir::AffineMapAttr::get(), and unwrap().
mlirAffineMapAttrGetValue()
MlirAffineMap mlirAffineMapAttrGetValue (MlirAttribute attr)
Returns the affine map wrapped in the given affine map attribute.
Definition at line 29 of file StandardAttributes.cpp.
References unwrap().
mlirArrayAttrGet()
MlirAttribute mlirArrayAttrGet (MlirContext ctx, intptr_t numElements, MlirAttribute * elements)
Creates an array element containing the given list of elements in the given context.
Definition at line 41 of file StandardAttributes.cpp.
References mlir::ArrayAttr::get(), unwrap(), and unwrapList().
mlirArrayAttrGetElement()
MlirAttribute mlirArrayAttrGetElement (MlirAttribute attr, intptr_t pos)
Returns pos-th element stored in the given array attribute.
Definition at line 53 of file StandardAttributes.cpp.
References unwrap().
mlirArrayAttrGetNumElements()
intptr_t mlirArrayAttrGetNumElements (MlirAttribute attr)
Returns the number of elements stored in the given array attribute.
Definition at line 49 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirAttributeIsAAffineMap()
int mlirAttributeIsAAffineMap (MlirAttribute attr)
Checks whether the given attribute is an affine map attribute.
Definition at line 21 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAArray()
int mlirAttributeIsAArray (MlirAttribute attr)
Checks whether the given attribute is an array attribute.
Definition at line 37 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsABool()
int mlirAttributeIsABool (MlirAttribute attr)
Checks whether the given attribute is a bool attribute.
Definition at line 128 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsADenseElements()
int mlirAttributeIsADenseElements (MlirAttribute attr)
Checks whether the given attribute is a dense elements attribute.
Definition at line 319 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsADenseFPElements()
int mlirAttributeIsADenseFPElements (MlirAttribute attr)
Definition at line 325 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsADenseIntElements()
int mlirAttributeIsADenseIntElements (MlirAttribute attr)
Definition at line 322 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsADictionary()
int mlirAttributeIsADictionary (MlirAttribute attr)
Checks whether the given attribute is a dictionary attribute.
Definition at line 61 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAElements()
int mlirAttributeIsAElements (MlirAttribute attr)
Checks whether the given attribute is an elements attribute.
Definition at line 292 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAFlatSymbolRef()
int mlirAttributeIsAFlatSymbolRef (MlirAttribute attr)
Checks whether the given attribute is a flat symbol reference attribute.
Definition at line 244 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAFloat()
int mlirAttributeIsAFloat (MlirAttribute attr)
Checks whether the given attribute is a floating point attribute.
Definition at line 95 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAInteger()
int mlirAttributeIsAInteger (MlirAttribute attr)
Checks whether the given attribute is an integer attribute.
Definition at line 112 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAIntegerSet()
int mlirAttributeIsAIntegerSet (MlirAttribute attr)
Checks whether the given attribute is an integer set attribute.
Definition at line 144 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAOpaque()
int mlirAttributeIsAOpaque (MlirAttribute attr)
Checks whether the given attribute is an opaque attribute.
Definition at line 152 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAOpaqueElements()
int mlirAttributeIsAOpaqueElements (MlirAttribute attr)
Checks whether the given attribute is an opaque elements attribute.
Definition at line 534 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsASparseElements()
int mlirAttributeIsASparseElements (MlirAttribute attr)
Checks whether the given attribute is a sparse elements attribute.
Definition at line 542 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAString()
int mlirAttributeIsAString (MlirAttribute attr)
Checks whether the given attribute is a string attribute.
Definition at line 178 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirAttributeIsASymbolRef()
int mlirAttributeIsASymbolRef (MlirAttribute attr)
Checks whether the given attribute is a symbol reference attribute.
Definition at line 202 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAType()
int mlirAttributeIsAType (MlirAttribute attr)
Checks whether the given attribute is a type attribute.
Definition at line 264 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirAttributeIsAUnit()
int mlirAttributeIsAUnit (MlirAttribute attr)
Checks whether the given attribute is a unit attribute.
Definition at line 280 of file StandardAttributes.cpp.
References mlir::Type::isa(), and unwrap().
mlirBoolAttrGet()
MlirAttribute mlirBoolAttrGet (MlirContext ctx, int value)
Creates a bool attribute in the given context with the given value.
Definition at line 132 of file StandardAttributes.cpp.
References mlir::BoolAttr::get(), and unwrap().
mlirBoolAttrGetValue()
int mlirBoolAttrGetValue (MlirAttribute attr)
Returns the value stored in the given bool attribute.
Definition at line 136 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrBoolGet()
MlirAttribute mlirDenseElementsAttrBoolGet (MlirType shapedType, intptr_t numElements, int * elements)
Creates a dense elements attribute with the given shaped type from elements of a specific type.
Expects the element type of the shaped type to match the data element type.
Definition at line 382 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrBoolSplatGet()
MlirAttribute mlirDenseElementsAttrBoolSplatGet (MlirType shapedType, int element)
Definition at line 346 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrDoubleGet()
MlirAttribute mlirDenseElementsAttrDoubleGet (MlirType shapedType, intptr_t numElements, double * elements)
Definition at line 424 of file StandardAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrDoubleSplatGet()
MlirAttribute mlirDenseElementsAttrDoubleSplatGet (MlirType shapedType, double element)
Definition at line 376 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrFloatGet()
MlirAttribute mlirDenseElementsAttrFloatGet (MlirType shapedType, intptr_t numElements, float * elements)
Definition at line 419 of file StandardAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrFloatSplatGet()
MlirAttribute mlirDenseElementsAttrFloatSplatGet (MlirType shapedType, float element)
Definition at line 371 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrGet()
MlirAttribute mlirDenseElementsAttrGet (MlirType shapedType, intptr_t numElements, MlirAttribute * elements)
Creates a dense elements attribute with the given Shaped type and elements in the same context as the type.
Definition at line 332 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), unwrap(), and unwrapList().
mlirDenseElementsAttrGetBoolSplatValue()
int mlirDenseElementsAttrGetBoolSplatValue (MlirAttribute attr)
Definition at line 459 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetBoolValue()
int mlirDenseElementsAttrGetBoolValue (MlirAttribute attr, intptr_t pos)
Returns the pos-th value (flat contiguous indexing) of a specific type contained by the given dense elements attribute.
Definition at line 491 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetDoubleSplatValue()
double mlirDenseElementsAttrGetDoubleSplatValue (MlirAttribute attr)
Definition at line 477 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetDoubleValue()
double mlirDenseElementsAttrGetDoubleValue (MlirAttribute attr, intptr_t pos)
Definition at line 517 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetFloatSplatValue()
float mlirDenseElementsAttrGetFloatSplatValue (MlirAttribute attr)
Definition at line 474 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetFloatValue()
float mlirDenseElementsAttrGetFloatValue (MlirAttribute attr, intptr_t pos)
Definition at line 513 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetInt32SplatValue()
int32_t mlirDenseElementsAttrGetInt32SplatValue (MlirAttribute attr)
Definition at line 462 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetInt32Value()
int32_t mlirDenseElementsAttrGetInt32Value (MlirAttribute attr, intptr_t pos)
Definition at line 495 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetInt64SplatValue()
int64_t mlirDenseElementsAttrGetInt64SplatValue (MlirAttribute attr)
Definition at line 468 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetInt64Value()
int64_t mlirDenseElementsAttrGetInt64Value (MlirAttribute attr, intptr_t pos)
Definition at line 504 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetSplatValue()
MlirAttribute mlirDenseElementsAttrGetSplatValue (MlirAttribute attr)
Returns the single replicated value (splat) of a specific type contained by the given dense elements attribute.
Definition at line 456 of file StandardAttributes.cpp.
References unwrap().
mlirDenseElementsAttrGetStringSplatValue()
void mlirDenseElementsAttrGetStringSplatValue (MlirAttribute attr, MlirStringCallback callback, void * userData)
Definition at line 480 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetStringValue()
void mlirDenseElementsAttrGetStringValue (MlirAttribute attr, intptr_t pos, MlirStringCallback callback, void * userData)
Definition at line 521 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetUInt32SplatValue()
uint32_t mlirDenseElementsAttrGetUInt32SplatValue (MlirAttribute attr)
Definition at line 465 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetUInt32Value()
uint32_t mlirDenseElementsAttrGetUInt32Value (MlirAttribute attr, intptr_t pos)
Definition at line 499 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetUInt64SplatValue()
uint64_t mlirDenseElementsAttrGetUInt64SplatValue (MlirAttribute attr)
Definition at line 471 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrGetUInt64Value()
uint64_t mlirDenseElementsAttrGetUInt64Value (MlirAttribute attr, intptr_t pos)
Definition at line 508 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrInt32Get()
MlirAttribute mlirDenseElementsAttrInt32Get (MlirType shapedType, intptr_t numElements, int32_t * elements)
Definition at line 404 of file StandardAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrInt32SplatGet()
MlirAttribute mlirDenseElementsAttrInt32SplatGet (MlirType shapedType, int32_t element)
Definition at line 356 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrInt64Get()
MlirAttribute mlirDenseElementsAttrInt64Get (MlirType shapedType, intptr_t numElements, int64_t * elements)
Definition at line 414 of file StandardAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrInt64SplatGet()
MlirAttribute mlirDenseElementsAttrInt64SplatGet (MlirType shapedType, int64_t element)
Definition at line 366 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrIsSplat()
int mlirDenseElementsAttrIsSplat (MlirAttribute attr)
Checks whether the given dense elements attribute contains a single replicated value (splat).
Definition at line 452 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDenseElementsAttrReshapeGet()
MlirAttribute mlirDenseElementsAttrReshapeGet (MlirAttribute attr, MlirType shapedType)
Creates a dense elements attribute that has the same data as the given dense elements attribute and a different shaped type.
The new type must have the same total number of elements.
Definition at line 443 of file StandardAttributes.cpp.
References unwrap().
mlirDenseElementsAttrSplatGet()
MlirAttribute mlirDenseElementsAttrSplatGet (MlirType shapedType, MlirAttribute element)
Creates a dense elements attribute with the given Shaped type containing a single replicated element (splat).
Definition at line 341 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrStringGet()
MlirAttribute mlirDenseElementsAttrStringGet (MlirType shapedType, intptr_t numElements, intptr_t * strLengths, const char ** strs)
Creates a dense elements attribute with the given shaped type from string elements.
The strings need not be null-terminated and their lengths are provided as a separate argument co-indexed with the strs argument.
Definition at line 430 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrUInt32Get()
MlirAttribute mlirDenseElementsAttrUInt32Get (MlirType shapedType, intptr_t numElements, uint32_t * elements)
Definition at line 399 of file StandardAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrUInt32SplatGet()
MlirAttribute mlirDenseElementsAttrUInt32SplatGet (MlirType shapedType, uint32_t element)
Definition at line 351 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDenseElementsAttrUInt64Get()
MlirAttribute mlirDenseElementsAttrUInt64Get (MlirType shapedType, intptr_t numElements, uint64_t * elements)
Definition at line 409 of file StandardAttributes.cpp.
References getDenseAttribute().
mlirDenseElementsAttrUInt64SplatGet()
MlirAttribute mlirDenseElementsAttrUInt64SplatGet (MlirType shapedType, uint64_t element)
Definition at line 361 of file StandardAttributes.cpp.
References mlir::DenseElementsAttr::get(), and unwrap().
mlirDictionaryAttrGet()
MlirAttribute mlirDictionaryAttrGet (MlirContext ctx, intptr_t numElements, MlirNamedAttribute * elements)
Creates a dictionary attribute containing the given list of elements in the provided context.
Definition at line 65 of file StandardAttributes.cpp.
References mlir::Identifier::get(), mlir::DictionaryAttr::get(), MlirNamedAttribute::name, and unwrap().
mlirDictionaryAttrGetElement()
MlirNamedAttribute mlirDictionaryAttrGetElement (MlirAttribute attr, intptr_t pos)
Returns pos-th element of the given dictionary attribute.
Definition at line 79 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirDictionaryAttrGetElementByName()
MlirAttribute mlirDictionaryAttrGetElementByName (MlirAttribute attr, const char * name)
Returns the dictionary attribute element with the given name or NULL if the given name does not exist in the dictionary.
Definition at line 86 of file StandardAttributes.cpp.
References unwrap().
mlirDictionaryAttrGetNumElements()
intptr_t mlirDictionaryAttrGetNumElements (MlirAttribute attr)
Returns the number of attributes contained in a dictionary attribute.
Definition at line 75 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirElementsAttrGetNumElements()
int64_t mlirElementsAttrGetNumElements (MlirAttribute attr)
Gets the total number of elements in the given elements attribute.
In order to iterate over the attribute, obtain its type, which must be a statically shaped type and use its sizes to build a multi-dimensional index.
Definition at line 308 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirElementsAttrGetValue()
MlirAttribute mlirElementsAttrGetValue (MlirAttribute attr, intptr_t rank, uint64_t * idxs)
Returns the element at the given rank-dimensional index.
Definition at line 296 of file StandardAttributes.cpp.
References unwrap().
mlirElementsAttrIsValidIndex()
int mlirElementsAttrIsValidIndex (MlirAttribute attr, intptr_t rank, uint64_t * idxs)
Checks whether the given rank-dimensional index is valid in the given elements attribute.
Definition at line 302 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirFlatSymbolRefAttrGet()
MlirAttribute mlirFlatSymbolRefAttrGet (MlirContext ctx, intptr_t length, const char * symbol)
Creates a flat symbol reference attribute in the given context referencing a symbol identified by the given string.
The string need not be null-terminated and its length must be specified.
Definition at line 248 of file StandardAttributes.cpp.
References mlir::FlatSymbolRefAttr::get(), and unwrap().
mlirFloatAttrDoubleGet()
MlirAttribute mlirFloatAttrDoubleGet (MlirContext ctx, MlirType type, double value)
Creates a floating point attribute in the given context with the given double value and double-precision FP semantics.
Definition at line 99 of file StandardAttributes.cpp.
References mlir::FloatAttr::get(), and unwrap().
mlirFloatAttrGetValueDouble()
double mlirFloatAttrGetValueDouble (MlirAttribute attr)
Returns the value stored in the given floating point attribute, interpreting the value as double.
Definition at line 104 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirFloatSymbolRefAttrGetValue()
void mlirFloatSymbolRefAttrGetValue (MlirAttribute attr, MlirStringCallback callback, void * userData)
Calls the provided callback with the string containing the referenced symbol.
The callback is invoked once, and the data it receives is not necessarily null terminated. The data remains live as long as the context in which the attribute lives.
Definition at line 253 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirIntegerAttrGet()
MlirAttribute mlirIntegerAttrGet (MlirType type, int64_t value)
Creates an integer attribute of the given type with the given integer value.
Definition at line 116 of file StandardAttributes.cpp.
References mlir::IntegerAttr::get(), and unwrap().
mlirIntegerAttrGetValueInt()
int64_t mlirIntegerAttrGetValueInt (MlirAttribute attr)
Returns the value stored in the given integer attribute, assuming the value fits into a 64-bit integer.
Definition at line 120 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirOpaqueAttrGet()
MlirAttribute mlirOpaqueAttrGet (MlirContext ctx, const char * dialectNamespace, intptr_t dataLength, const char * data, MlirType type)
Creates an opaque attribute in the given context associated with the dialect identified by its namespace.
The attribute contains opaque byte data of the specified length (data need not be null-terminated).
Definition at line 156 of file StandardAttributes.cpp.
References mlir::Identifier::get(), mlir::OpaqueAttr::get(), and unwrap().
mlirOpaqueAttrGetData()
void mlirOpaqueAttrGetData (MlirAttribute attr, MlirStringCallback callback, void * userData)
Calls the provided callback with the opaque byte data stored in the given opaque attribute.
The callback is invoked once, and the data it receives is not necessarily null terminated. The data remains live as long as the context in which the attribute lives.
Definition at line 168 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirOpaqueAttrGetDialectNamespace()
const char* mlirOpaqueAttrGetDialectNamespace (MlirAttribute attr)
Returns the namepsace of the dialect with which the given opaque attribute is associated.
The namespace string is owned by the context.
Definition at line 164 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirSparseElementsAttrGetIndices()
MlirAttribute mlirSparseElementsAttrGetIndices (MlirAttribute attr)
Returns the dense elements attribute containing 64-bit integer indices of non-null elements in the given sparse elements attribute.
Definition at line 555 of file StandardAttributes.cpp.
References unwrap().
mlirSparseElementsAttrGetValues()
MlirAttribute mlirSparseElementsAttrGetValues (MlirAttribute attr)
Returns the dense elements attribute containing the non-null elements in the given sparse elements attribute.
Definition at line 559 of file StandardAttributes.cpp.
References unwrap().
mlirSparseElementsAttribute()
MlirAttribute mlirSparseElementsAttribute (MlirType shapedType, MlirAttribute denseIndices, MlirAttribute denseValues)
Creates a sparse elements attribute of the given shape from a list of indices and a list of associated values.
Both lists are expected to be dense elements attributes with the same number of elements. The list of indices is expected to contain 64-bit integers. The attribute is created in the same context as the type.
Definition at line 546 of file StandardAttributes.cpp.
References mlir::SparseElementsAttr::get(), and unwrap().
mlirStringAttrGet()
MlirAttribute mlirStringAttrGet (MlirContext ctx, intptr_t length, const char * data)
Creates a string attribute in the given context containing the given string.
The string need not be null-terminated and its length must be specified.
Definition at line 182 of file StandardAttributes.cpp.
References mlir::StringAttr::get(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirStringAttrGetValue()
void mlirStringAttrGetValue (MlirAttribute attr, MlirStringCallback callback, void * userData)
Calls the provided callback with the string stored in the given string attribute.
The callback is invoked once, and the data it receives is not necessarily null terminated. The data remains live as long as the context in which the attribute lives.
Definition at line 192 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirStringAttrTypedGet()
MlirAttribute mlirStringAttrTypedGet (MlirType type, intptr_t length, const char * data)
Creates a string attribute in the given context containing the given string.
The string need not be null-terminated and its length must be specified. Additionally, the attribute has the given type.
Definition at line 187 of file StandardAttributes.cpp.
References mlir::StringAttr::get(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirSymbolRefAttrGet()
MlirAttribute mlirSymbolRefAttrGet (MlirContext ctx, intptr_t length, const char * symbol, intptr_t numReferences, MlirAttribute * references)
Creates a symbol reference attribute in the given context referencing a symbol identified by the given string inside a list of nested references.
Each of the references in the list must not be nested. The string need not be null-terminated and its length must be specified.
Definition at line 206 of file StandardAttributes.cpp.
References mlir::SymbolRefAttr::get(), and unwrap().
mlirSymbolRefAttrGetLeafReference()
void mlirSymbolRefAttrGetLeafReference (MlirAttribute attr, MlirStringCallback callback, void * userData)
Calls the provided callback with the string containing the leaf referenced symbol.
The callback is invoked once, and the data it receives is not necessarily null terminated. The data remains live as long as the context in which the attribute lives.
Definition at line 223 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirSymbolRefAttrGetNestedReference()
MlirAttribute mlirSymbolRefAttrGetNestedReference (MlirAttribute attr, intptr_t pos)
Returns pos-th reference nested in the given symbol reference attribute.
Definition at line 235 of file StandardAttributes.cpp.
References unwrap().
mlirSymbolRefAttrGetNumNestedReferences()
intptr_t mlirSymbolRefAttrGetNumNestedReferences (MlirAttribute attr)
Returns the number of references nested in the given symbol reference attribute.
Definition at line 230 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirSymbolRefAttrGetRootReference()
void mlirSymbolRefAttrGetRootReference (MlirAttribute attr, MlirStringCallback callback, void * userData)
Calls the provided callback with the string containing the root referenced symbol.
The callback is invoked once, and the data it receives is not necessarily null terminated. The data remains live as long as the context in which the attribute lives.
Definition at line 216 of file StandardAttributes.cpp.
References mlir::Type::cast(), and unwrap().
mlirTypeAttrGet()
MlirAttribute mlirTypeAttrGet (MlirType type)
Creates a type attribute wrapping the given type in the same context as the type.
Definition at line 268 of file StandardAttributes.cpp.
References mlir::TypeAttr::get(), and unwrap().
mlirTypeAttrGetValue()
MlirType mlirTypeAttrGetValue (MlirAttribute attr)
Returns the type stored in the given type attribute.
Definition at line 272 of file StandardAttributes.cpp.
References unwrap().
mlirUnitAttrGet()
MlirAttribute mlirUnitAttrGet (MlirContext ctx)
Creates a unit attribute in the given context.
Definition at line 284 of file StandardAttributes.cpp.
References mlir::UnitAttr::get(), and unwrap().