MLIR: mlir::detail::OpPassManagerImpl Struct Reference
mlir::detail::OpPassManagerImpl Struct Reference
Public Member Functions
OpPassManagerImpl (Identifier identifier, bool verifyPasses)
OpPassManagerImpl (StringRef name, bool verifyPasses)
void mergeInto (OpPassManagerImpl &rhs)
Merge the passes of this pass manager into the one provided.
OpPassManager & nest (Identifier nestedName)
Nest a new operation pass manager for the given operation kind under this pass manager.
OpPassManager & nest (StringRef nestedName)
void addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
void coalesceAdjacentAdaptorPasses ()
Coalesce adjacent AdaptorPasses into one large adaptor.
void splitAdaptorPasses ()
Split all of AdaptorPasses such that each adaptor only contains one leaf pass.
Identifier getOpName (MLIRContext &context)
Public Attributes
StringRef name
The name of the operation that passes of this pass manager operate on.
Optional< Identifier > identifier
The cached identifier (internalized in the context) for the name of the operation that passes of this pass manager operate on.
bool verifyPasses: 1
Flag that specifies if the IR should be verified after each pass has run.
std::vector< std::unique_ptr< Pass > > passes
The set of passes to run as part of this pass manager.
Detailed Description
Definition at line 94 of file Pass.cpp.
Constructor & Destructor Documentation
OpPassManagerImpl() [1/2]
mlir::detail::OpPassManagerImpl::OpPassManagerImpl (Identifier identifier, bool verifyPasses) inline
Definition at line 95 of file Pass.cpp.
OpPassManagerImpl() [2/2]
mlir::detail::OpPassManagerImpl::OpPassManagerImpl (StringRef name, bool verifyPasses) inline
Definition at line 97 of file Pass.cpp.
Member Function Documentation
addPass()
void OpPassManagerImpl::addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
If this pass has a concrete operation type, it must be the same type as this pass manager.
Definition at line 163 of file Pass.cpp.
coalesceAdjacentAdaptorPasses()
void OpPassManagerImpl::coalesceAdjacentAdaptorPasses ()
Coalesce adjacent AdaptorPasses into one large adaptor.
This runs recursively through the pipeline graph.
Definition at line 175 of file Pass.cpp.
References mlir::detail::OpToOpPassAdaptor::getPassManagers(), and mlir::detail::OpToOpPassAdaptor::mergeInto().
Referenced by mlir::PassManager::run().
getOpName()
Identifier mlir::detail::OpPassManagerImpl::getOpName (MLIRContext & context) inline
Definition at line 120 of file Pass.cpp.
References mlir::Identifier::get().
mergeInto()
void OpPassManagerImpl::mergeInto (OpPassManagerImpl & rhs)
Merge the passes of this pass manager into the one provided.
Definition at line 142 of file Pass.cpp.
References name, and passes.
nest() [1/2]
OpPassManager & OpPassManagerImpl::nest (Identifier nestedName)
Nest a new operation pass manager for the given operation kind under this pass manager.
Definition at line 149 of file Pass.cpp.
nest() [2/2]
OpPassManager & OpPassManagerImpl::nest (StringRef nestedName)
Definition at line 156 of file Pass.cpp.
splitAdaptorPasses()
void OpPassManagerImpl::splitAdaptorPasses ()
Split all of AdaptorPasses such that each adaptor only contains one leaf pass.
Definition at line 225 of file Pass.cpp.
Member Data Documentation
identifier
Optional<Identifier> mlir::detail::OpPassManagerImpl::identifier
The cached identifier (internalized in the context) for the name of the operation that passes of this pass manager operate on.
Definition at line 131 of file Pass.cpp.
name
StringRef mlir::detail::OpPassManagerImpl::name
The name of the operation that passes of this pass manager operate on.
Definition at line 127 of file Pass.cpp.
Referenced by mergeInto().
passes
std::vector<std::unique_ptr<Pass> > mlir::detail::OpPassManagerImpl::passes
The set of passes to run as part of this pass manager.
Definition at line 137 of file Pass.cpp.
Referenced by mergeInto().
verifyPasses
bool mlir::detail::OpPassManagerImpl::verifyPasses
Flag that specifies if the IR should be verified after each pass has run.
Definition at line 134 of file Pass.cpp.
The documentation for this struct was generated from the following file:
lib/Pass/Pass.cpp