MLIR: mlir::LowerVectorToLLVMOptions Struct Reference
mlir::LowerVectorToLLVMOptions Struct Reference
Options to control Vector to LLVM lowering.
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
Public Member Functions
LowerVectorToLLVMOptions & setReassociateFPReductions (bool b)
LowerVectorToLLVMOptions & setEnableIndexOptimizations (bool b)
Public Attributes
bool reassociateFPReductions = false
bool enableIndexOptimizations = false
Detailed Description
Options to control Vector to LLVM lowering.
This should kept in sync with VectorToLLVM options defined for the ConvertVectorToLLVM pass in include/mlir/Conversion/Passes.td
Definition at line 23 of file ConvertVectorToLLVM.h.
Member Function Documentation
setEnableIndexOptimizations()
LowerVectorToLLVMOptions& mlir::LowerVectorToLLVMOptions::setEnableIndexOptimizations (bool b) inline
Definition at line 30 of file ConvertVectorToLLVM.h.
References mlir::createConvertVectorToLLVMPass(), enableIndexOptimizations, options, mlir::populateVectorToLLVMConversionPatterns(), mlir::populateVectorToLLVMMatrixConversionPatterns(), and reassociateFPReductions.
setReassociateFPReductions()
LowerVectorToLLVMOptions& mlir::LowerVectorToLLVMOptions::setReassociateFPReductions (bool b) inline
Definition at line 26 of file ConvertVectorToLLVM.h.
Member Data Documentation
enableIndexOptimizations
bool mlir::LowerVectorToLLVMOptions::enableIndexOptimizations = false
Definition at line 25 of file ConvertVectorToLLVM.h.
Referenced by mlir::populateVectorToLLVMMatrixConversionPatterns(), and setEnableIndexOptimizations().
reassociateFPReductions
bool mlir::LowerVectorToLLVMOptions::reassociateFPReductions = false
Definition at line 24 of file ConvertVectorToLLVM.h.
Referenced by mlir::populateVectorToLLVMMatrixConversionPatterns(), and setEnableIndexOptimizations().
The documentation for this struct was generated from the following file:
include/mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h