MLIR: lib/Conversion/VectorToSCF/VectorToSCF.cpp File Reference
VectorToSCF.cpp File Reference
#include <type_traits>
#include "mlir/Conversion/VectorToSCF/VectorToSCF.h"
#include "../PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/SCF/EDSC/Intrinsics.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/Passes.h"
Namespaces
mlir
Macros
#define ALIGNMENT_SIZE 128
Functions
template<typename TransferOpTy >
static int computeCoalescedIndex (TransferOpTy transfer)
Analyzes the transfer to find an access dimension along the fastest remote MemRef dimension.
template<typename TransferOpTy >
static SmallVector< Value, 8 > clip (TransferOpTy transfer, MemRefBoundsCapture &bounds, ArrayRef< Value > ivs)
Emits remote memory accesses that are clipped to the boundaries of the MemRef.
void mlir::populateVectorToSCFConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *context, const VectorTransferToSCFOptions &options=VectorTransferToSCFOptions())
Collect a set of patterns to convert from the Vector dialect to SCF + std.
Macro Definition Documentation
ALIGNMENT_SIZE
#define ALIGNMENT_SIZE 128
Definition at line 38 of file VectorToSCF.cpp.
Referenced by mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().
Function Documentation
clip()
template<typename TransferOpTy > static SmallVector<Value, 8> clip (TransferOpTy transfer, MemRefBoundsCapture & bounds, ArrayRef< Value > ivs) static
Emits remote memory accesses that are clipped to the boundaries of the MemRef.
Definition at line 434 of file VectorToSCF.cpp.
References mlir::detail::enumerate(), mlir::edsc::op::slt(), and mlir::edsc::BoundsCapture::ub().
Referenced by mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().
computeCoalescedIndex()
template<typename TransferOpTy > static int computeCoalescedIndex (TransferOpTy transfer) static
Analyzes the transfer to find an access dimension along the fastest remote MemRef dimension.
If such a dimension with coalescing properties is found, pivs and vectorBoundsCapture are swapped so that the invocation of LoopNestBuilder captures it in the innermost loop.
Definition at line 405 of file VectorToSCF.cpp.
References mlir::detail::enumerate(), and mlir::AffineDimExpr::getPosition().
Referenced by mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().